/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check (DB + Redis reachable) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Called by Clerk (via Svix), not by the frontend. Verified with the `svix-id`, `svix-timestamp`
         *     and `svix-signature` headers against CLERK_WEBHOOK_SIGNING_SECRET, using the raw request body.
         *     Handles `user.updated` (sync email) and `user.deleted` (deactivate). Other event types → 204, ignored.
         *     Idempotent on `svix-id`. Deliveries may repeat or arrive out of order.
         */
        post: operations["clerkWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * First call after a new Clerk sign-up. Creates the RideMatch user row, linked to the token's `sub`
         *     (Clerk user id), with the email from the token's `email` claim. Until this succeeds, every other
         *     authenticated endpoint returns 403 ONBOARDING_REQUIRED. If the email equals ADMIN_EMAIL and no admin exists yet,
         *     the user is created with is_admin=true. Sends the `welcome` notification + email.
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The frontend calls this right after Clerk sign-in. 403 ONBOARDING_REQUIRED → show the onboarding form. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile and/or preferences (preferences are shallow-merged; notifications sub-object merged too) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counters for driver Home and passenger Profile screens */
        get: operations["getMyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUserRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Driver offers a ride. status=upcoming, available_seats=capacity.
         *     The caller must have a vehicle on their profile (409 VEHICLE_REQUIRED).
         */
        post: operations["createRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rides the caller offers as driver, ordered by departure_time ascending */
        get: operations["listMyRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{ride_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Driver only, status must be `upcoming` or `full`. If the ride has approved passengers,
         *     location/departure_time changes → 409 RIDE_HAS_APPROVED_PASSENGERS, and capacity may not drop
         *     below approved seats → 409 CAPACITY_BELOW_APPROVED. Changing capacity recomputes available_seats
         *     and status (full ↔ upcoming).
         */
        patch: operations["updateRide"];
        trace?: never;
    };
    "/rides/{ride_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Driver only, from `upcoming` or `full`. Sets status=cancelled, all pending/approved requests →
         *     cancelled, notifies approved passengers (ride_cancelled) and pending requesters.
         */
        post: operations["cancelRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{ride_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Driver only, from `upcoming`/`full`, on departure day. Pending requests → rejected. */
        post: operations["startRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{ride_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Driver only, from `in_progress`. Opens rating for all participants. */
        post: operations["completeRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{ride_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver of the ride only. All requests on the ride, newest first. */
        get: operations["listRideRequests"];
        put?: never;
        /**
         * Passenger requests seats. Rejected with 409 if: caller is the driver (CANNOT_REQUEST_OWN_RIDE),
         *     ride not `upcoming` (RIDE_NOT_OPEN), not enough seats (NOT_ENOUGH_SEATS), caller already has
         *     a pending/approved request on this ride (REQUEST_ALREADY_EXISTS), or the driver already rejected
         *     the caller on this ride (PREVIOUSLY_REJECTED). Re-requesting after the caller's own cancel is allowed.
         *     Notifies driver (request_created).
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Passenger's trips (My Trips), newest first */
        get: operations["listMyRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requests on all of the caller's rides (driver Requests tab + Home badge). Default status=pending. */
        get: operations["listIncomingRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visible to the passenger who made it and the ride's driver */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Driver only, request must be `pending`, ride `upcoming`. Decrements available_seats by
         *     seats_requested under a row lock (409 NOT_ENOUGH_SEATS otherwise); ride → `full` at 0.
         *     Notifies passenger (request_approved + email).
         */
        post: operations["approveRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Driver only, request must be `pending`. Notifies passenger (request_rejected + email). */
        post: operations["rejectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Passenger only. `pending` → cancelled any time before the ride starts.
         *     `approved` → cancelled only until departure_time − 1h (409 TOO_LATE_TO_CANCEL after that);
         *     the seats go back to the ride (full → upcoming if it was full). Notifies driver (request_cancelled).
         */
        post: operations["cancelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scores `upcoming` rides with enough seats near the passenger's route/time. Excludes the
         *     caller's own rides and rides the caller already has a pending/approved request on.
         *     Returns only match_score ≥ 40. Passenger preferences come from the caller's saved preferences.
         */
        get: operations["searchRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ride must be `completed`. Caller and to_user must both be participants (driver or approved
         *     passenger) and not the same person; driver rates passengers, passengers rate the driver
         *     (passenger↔passenger not allowed → 403 NOT_A_PARTICIPANT). role_rated is derived server-side.
         *     Updates the ratee's cached rating. One per direction per ride (409 ALREADY_RATED).
         */
        post: operations["createRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ratings the caller still owes on completed rides (drives the post-ride prompt) */
        get: operations["listPendingRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        /** Clear all (deletes the caller's notifications) */
        delete: operations["clearNotifications"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUnreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin only. Total count in `X-Total-Count` header. */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets is_active=false and bans the user in Clerk (Backend API), which ends their sessions. Admin cannot deactivate self (409 CANNOT_DEACTIVATE_SELF). */
        post: operations["adminDeactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets is_active=true and unbans the user in Clerk. */
        post: operations["adminReactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin only. Total count in `X-Total-Count` header. */
        get: operations["adminListRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rides/{ride_id}/force-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel any non-terminal ride (incl. in_progress). Same side effects as driver cancel, plus notifies the driver. */
        post: operations["adminForceCancelRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Stable machine-readable code (see CONTRACT.md §5)
             * @example RIDE_NOT_OPEN
             */
            code: string;
            /** @description Human-readable, not for parsing */
            message: string;
            /** @description For VALIDATION_ERROR — list of field errors */
            details?: {
                /** @example body.departure_time */
                field: string;
                message: string;
            }[];
        };
        Latitude: number;
        Longitude: number;
        /**
         * @description Decimal as string, e.g. "25.50" (never a float)
         * @example 25.50
         */
        Money: string;
        /**
         * @description Unverified profile field (SMS verification is out of scope for v1). The same format applies
         *     wherever a phone is written — onboarding and PATCH /users/me alike.
         *     Allowed: digits, spaces, hyphens, parentheses, dots, and an optional leading `+`.
         *     7-20 characters after the `+`, so parenthesised and dotted formats are accepted as typed.
         * @example +972 50-123-4567
         * @example 050-123-4567
         * @example +1 (555) 010-9999
         * @example +1.555.0199
         */
        Phone: string;
        /** @enum {string} */
        Gender: "male" | "female" | "other" | "prefer_not_to_say";
        /** @enum {string} */
        Mode: "driver" | "passenger";
        /** @enum {string} */
        RoleRated: "driver" | "passenger";
        /** @enum {string} */
        RideStatus: "upcoming" | "full" | "in_progress" | "completed" | "cancelled";
        /** @enum {string} */
        RequestStatus: "pending" | "approved" | "rejected" | "cancelled";
        /** @enum {string} */
        NotificationType: "welcome" | "request_created" | "request_approved" | "request_rejected" | "request_cancelled" | "ride_reminder" | "ride_cancelled" | "ride_started" | "ride_completed" | "rating_received";
        /** @description Email and password are NOT here, since they live in Clerk. Frontend may prefill name from Clerk. */
        OnboardingRequest: {
            name: string;
            phone?: components["schemas"]["Phone"] | null;
            /**
             * Format: date
             * @description Must be 18+ today (422 UNDERAGE)
             */
            date_of_birth: string;
            gender?: components["schemas"]["Gender"] | null;
            preferences?: components["schemas"]["UserPreferencesPatch"];
            /** @description Optional here; required before offering a ride */
            vehicle?: components["schemas"]["Vehicle"] | null;
            /** @constant */
            accepted_terms: true;
        };
        NotificationPrefs: {
            /** @default true */
            email: boolean;
            /** @default true */
            push: boolean;
            /** @default true */
            websocket: boolean;
        };
        /**
         * @description Read shape: the server fills every default, so all keys are present in a response.
         *     Writes use UserPreferencesPatch instead.
         */
        UserPreferences: {
            /** @description null → client shows Role Selection */
            default_mode?: components["schemas"]["Mode"] | null;
            /**
             * @description true = OK with smoking
             * @default false
             */
            smoking: boolean;
            /**
             * @description true = OK with pets
             * @default false
             */
            pets: boolean;
            notifications?: components["schemas"]["NotificationPrefs"];
            /**
             * @default en
             * @example en
             * @example he
             */
            language: string;
            /**
             * @default system
             * @enum {string}
             */
            theme: "light" | "dark" | "system";
        };
        /**
         * @description Write shape for NotificationPrefs. No defaults, so an absent key means "leave it alone";
         *     the server merges what is sent into the stored sub-object.
         */
        NotificationPrefsPatch: {
            email?: boolean;
            push?: boolean;
            websocket?: boolean;
        };
        /**
         * @description Write shape for UserPreferences, used by PATCH /users/me and POST /users/me/onboarding.
         *     Shallow merge, with the `notifications` sub-object merged too (CONTRACT.md §4 Users).
         *     Carries no defaults — that is what separates it from UserPreferences, which is the read
         *     shape and always comes back complete. An absent key is left alone; `default_mode: null`
         *     genuinely clears it.
         */
        UserPreferencesPatch: {
            /** @description null → client shows Role Selection */
            default_mode?: components["schemas"]["Mode"] | null;
            /** @description true = OK with smoking */
            smoking?: boolean;
            /** @description true = OK with pets */
            pets?: boolean;
            notifications?: components["schemas"]["NotificationPrefsPatch"];
            /**
             * @example en
             * @example he
             */
            language?: string;
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
        };
        Vehicle: {
            /** @example Toyota */
            make: string;
            /** @example Corolla */
            model: string;
            /** @example White */
            color: string;
            /**
             * @description Stored as entered (trimmed, uppercased). Never in public views.
             * @example 12-345-67
             */
            plate: string;
        };
        /** @description Vehicle without the plate — what anyone may see */
        VehiclePublic: {
            make: string;
            model: string;
            color: string;
        };
        /** @description The caller's own full profile (also used in admin views). Email mirrors the Clerk primary email. */
        UserMe: {
            id: number;
            /** Format: email */
            email: string;
            name: string;
            phone?: string | null;
            /** Format: date */
            date_of_birth?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            is_admin: boolean;
            is_active: boolean;
            driver_rating?: number | null;
            driver_rating_count: number;
            passenger_rating?: number | null;
            passenger_rating_count: number;
            preferences: components["schemas"]["UserPreferences"];
            vehicle?: components["schemas"]["Vehicle"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        /** @description What other users may see. No email/phone/DOB. */
        UserPublic: {
            id: number;
            name: string;
            driver_rating?: number | null;
            driver_rating_count: number;
            passenger_rating?: number | null;
            passenger_rating_count: number;
            vehicle?: components["schemas"]["VehiclePublic"] | null;
            /**
             * Format: date-time
             * @description "Member since"
             */
            created_at: string;
        };
        /** @description Email and password are changed in Clerk (UserProfile component), not here. is_admin/is_active are admin-only. */
        UserUpdate: {
            name?: string;
            phone?: components["schemas"]["Phone"] | null;
            gender?: components["schemas"]["Gender"] | null;
            preferences?: components["schemas"]["UserPreferencesPatch"];
            /** @description Full replace. null removes it (409 VEHICLE_REQUIRED if the user has upcoming/full rides). */
            vehicle?: components["schemas"]["Vehicle"] | null;
        };
        UserStats: {
            as_driver: {
                rides_offered: number;
                rides_completed: number;
                upcoming_rides: number;
                /** @description Home badge */
                pending_requests: number;
                /** @description Sum of approved seats on completed rides */
                passengers_carried: number;
            };
            as_passenger: {
                trips_requested: number;
                trips_completed: number;
                upcoming_trips: number;
            };
        };
        RidePreferences: {
            /**
             * @description true = smoking allowed
             * @default false
             */
            smoking: boolean;
            /**
             * @description true = pets allowed
             * @default false
             */
            pets: boolean;
            /** @default true */
            music: boolean;
            /**
             * @description true = only passengers of the driver's gender (hard filter in matching)
             * @default false
             */
            gender_only: boolean;
        };
        /**
         * @description Write shape for RidePreferences, used by POST /rides and PATCH /rides/{ride_id}. No
         *     defaults: on create the server fills them, and on PATCH an absent key is left alone —
         *     a shallow merge of all four keys, exactly like user preferences (CONTRACT.md §4 Rides).
         */
        RidePreferencesPatch: {
            /** @description true = smoking allowed */
            smoking?: boolean;
            /** @description true = pets allowed */
            pets?: boolean;
            music?: boolean;
            /** @description true = only passengers of the driver's gender (hard filter in matching) */
            gender_only?: boolean;
        };
        RideCreate: {
            start_lat: components["schemas"]["Latitude"];
            start_lng: components["schemas"]["Longitude"];
            start_address: string;
            end_lat: components["schemas"]["Latitude"];
            end_lng: components["schemas"]["Longitude"];
            end_address: string;
            /**
             * Format: date-time
             * @description Must be in the future (422 DEPARTURE_IN_PAST)
             */
            departure_time: string;
            capacity: number;
            price_per_seat: components["schemas"]["Money"];
            preferences?: components["schemas"]["RidePreferencesPatch"];
            notes?: string | null;
        };
        /** @description All fields optional; see PATCH /rides/{id} for restrictions */
        RideUpdate: {
            start_lat?: components["schemas"]["Latitude"];
            start_lng?: components["schemas"]["Longitude"];
            start_address?: string;
            end_lat?: components["schemas"]["Latitude"];
            end_lng?: components["schemas"]["Longitude"];
            end_address?: string;
            /** Format: date-time */
            departure_time?: string;
            capacity?: number;
            price_per_seat?: components["schemas"]["Money"];
            preferences?: components["schemas"]["RidePreferencesPatch"];
            notes?: string | null;
        };
        Ride: {
            id: number;
            driver: components["schemas"]["UserPublic"];
            start_lat: components["schemas"]["Latitude"];
            start_lng: components["schemas"]["Longitude"];
            start_address: string;
            end_lat: components["schemas"]["Latitude"];
            end_lng: components["schemas"]["Longitude"];
            end_address: string;
            /** Format: date-time */
            departure_time: string;
            capacity: number;
            available_seats: number;
            price_per_seat: components["schemas"]["Money"];
            status: components["schemas"]["RideStatus"];
            preferences: components["schemas"]["RidePreferences"];
            notes?: string | null;
            /** @description Only filled for the driver and for passengers with an approved request on this ride; null for everyone else */
            driver_vehicle_plate?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ScoreBreakdown: {
            route: number;
            time: number;
            price: number;
            rating: number;
            preferences: number;
        };
        RideMatch: {
            ride: components["schemas"]["Ride"];
            /** @description Rounded to 1 decimal */
            match_score: number;
            breakdown: components["schemas"]["ScoreBreakdown"];
            pickup_distance_km: number;
            dropoff_distance_km: number;
        };
        RideRequestCreate: {
            /** @default 1 */
            seats_requested: number;
        };
        RideRequest: {
            id: number;
            ride: components["schemas"]["Ride"];
            passenger: components["schemas"]["UserPublic"];
            seats_requested: number;
            status: components["schemas"]["RequestStatus"];
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            responded_at?: string | null;
        };
        RatingCreate: {
            ride_id: number;
            to_user_id: number;
            score: number;
            comment?: string | null;
            /**
             * @example [
             *       "on_time",
             *       "clean_car",
             *       "friendly"
             *     ]
             */
            tags?: string[];
        };
        Rating: {
            id: number;
            ride_id: number;
            from_user: components["schemas"]["UserPublic"];
            to_user_id: number;
            role_rated: components["schemas"]["RoleRated"];
            score: number;
            comment?: string | null;
            tags: string[];
            /** Format: date-time */
            created_at: string;
        };
        PendingRating: {
            ride: components["schemas"]["Ride"];
            to_user: components["schemas"]["UserPublic"];
            role_rated: components["schemas"]["RoleRated"];
        };
        Notification: {
            id: number;
            type: components["schemas"]["NotificationType"];
            title: string;
            message: string;
            /** @enum {string|null} */
            related_entity_type?: "ride" | "ride_request" | null;
            related_entity_id?: number | null;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Messages the server sends on `GET /ws?token=<access_token>` (see CONTRACT.md §6).
         *     Not an HTTP endpoint — defined here so all sides share the payload shape.
         */
        WsServerMessage: {
            /** @constant */
            event: "notification";
            data: components["schemas"]["Notification"];
        } | {
            /** @constant */
            event: "pong";
        };
        AdminUserDetail: {
            user: components["schemas"]["UserMe"];
            rides_as_driver: components["schemas"]["Ride"][];
            requests_as_passenger: components["schemas"]["RideRequest"][];
            ratings_received: components["schemas"]["Rating"][];
        };
        AnalyticsSummary: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            rides_created: number;
            rides_completed: number;
            rides_cancelled: number;
            /** @description completed / (completed + cancelled) among rides departing in range; null if 0 */
            completion_rate: number | null;
            requests_created: number;
            /** @description approved / (approved + rejected) */
            approval_rate: number | null;
            /** @description Users with last_login_at in range */
            active_users: number;
            new_users: number;
        };
    };
    responses: {
        /** @description Missing, invalid or expired Clerk session token (UNAUTHENTICATED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed (FORBIDDEN, ONBOARDING_REQUIRED, ACCOUNT_DEACTIVATED, NOT_A_PARTICIPANT) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or is not visible to the caller) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Business-rule / state conflict — see `code` */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body/params failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        UserId: number;
        RideId: number;
        RequestId: number;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: {
        /** @description Total number of matching rows, ignoring limit/offset */
        XTotalCount: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        db: boolean;
                        redis: boolean;
                    };
                };
            };
        };
    };
    clerkWebhook: {
        parameters: {
            query?: never;
            header: {
                "svix-id": string;
                "svix-timestamp": string;
                "svix-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example user.updated */
                    type: string;
                    data: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Processed (or ignored) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad or missing signature (INVALID_WEBHOOK_SIGNATURE) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUserPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUserRatings: {
        parameters: {
            query?: {
                role_rated?: components["schemas"]["RoleRated"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ratings received by the user, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listMyRides: {
        parameters: {
            query?: {
                /** @description Comma-separated filter, e.g. `upcoming,full` */
                status?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rides */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ride */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    cancelRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    startRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started (status=in_progress) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    completeRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listRideRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"];
            };
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideRequestCreate"];
            };
        };
        responses: {
            /** @description Created (status=pending) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listMyRequests: {
        parameters: {
            query?: {
                /** @description Comma-separated filter, e.g. `pending,approved` */
                status?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listIncomingRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests, grouped client-side by ride_id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    approveRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    searchRides: {
        parameters: {
            query: {
                start_lat: components["schemas"]["Latitude"];
                start_lng: components["schemas"]["Longitude"];
                end_lat: components["schemas"]["Latitude"];
                end_lng: components["schemas"]["Longitude"];
                /** @description Desired departure time (ISO 8601 with offset) */
                time: string;
                /** @description Max acceptable price per seat */
                budget?: components["schemas"]["Money"];
                seats?: number;
                sort?: "best_match" | "earliest" | "cheapest";
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideMatch"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    createRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listPendingRatings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending ratings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRating"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    clearNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUnreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Badge count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        count: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /** @description Substring match on name or email */
                q?: string;
                is_active?: boolean;
                is_admin?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User with ride/request/rating history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminDeactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminReactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListRides: {
        parameters: {
            query?: {
                /** @description Comma-separated */
                status?: string;
                driver_id?: number;
                /** @description departure_time ≥ */
                from?: string;
                /** @description departure_time < */
                to?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rides */
            200: {
                headers: {
                    "X-Total-Count": components["headers"]["XTotalCount"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminForceCancelRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ride_id: components["parameters"]["RideId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminAnalytics: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
}
