"""initial schema

Mirrors contracts/schema.sql statement for statement, so the database Alembic builds and the
reference schema can't drift. `alembic check` against the SQLAlchemy models proves they agree.

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-01
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# One statement per entry: the asyncpg driver executes a single statement per call.
UPGRADE_STATEMENTS = (
    # ── updated_at helper ──
    """
    CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
    """,
    # ── users ──
    """
    CREATE TABLE users (
        id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id           varchar(64)  NOT NULL,
        email                   varchar(255) NOT NULL,
        is_admin                boolean      NOT NULL DEFAULT false,
        name                    varchar(100) NOT NULL,
        phone                   varchar(20),
        date_of_birth           date         NOT NULL,
        gender                  varchar(20)
            CONSTRAINT users_gender_check
            CHECK (gender IN ('male', 'female', 'other', 'prefer_not_to_say')),
        is_active               boolean      NOT NULL DEFAULT true,
        terms_accepted_at       timestamptz  NOT NULL,
        driver_rating           double precision
            CONSTRAINT users_driver_rating_check CHECK (driver_rating BETWEEN 1 AND 5),
        driver_rating_count     integer      NOT NULL DEFAULT 0
            CONSTRAINT users_driver_rating_count_check CHECK (driver_rating_count >= 0),
        passenger_rating        double precision
            CONSTRAINT users_passenger_rating_check CHECK (passenger_rating BETWEEN 1 AND 5),
        passenger_rating_count  integer      NOT NULL DEFAULT 0
            CONSTRAINT users_passenger_rating_count_check CHECK (passenger_rating_count >= 0),
        preferences             jsonb,
        vehicle                 jsonb,
        created_at              timestamptz  NOT NULL DEFAULT now(),
        updated_at              timestamptz  NOT NULL DEFAULT now(),
        last_login_at           timestamptz
    )
    """,
    "CREATE UNIQUE INDEX users_clerk_user_id_uq ON users (clerk_user_id)",
    # Case-insensitive uniqueness: the app lowercases email before insert/lookup.
    "CREATE UNIQUE INDEX users_email_lower_uq ON users (lower(email))",
    """
    CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """,
    # Idempotency log for Clerk webhooks (svix-id), so retried deliveries are processed once.
    """
    CREATE TABLE clerk_webhook_events (
        svix_id      varchar(100) PRIMARY KEY,
        event_type   varchar(100) NOT NULL,
        received_at  timestamptz  NOT NULL DEFAULT now()
    )
    """,
    # ── rides ──
    """
    CREATE TABLE rides (
        id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        driver_id       integer       NOT NULL REFERENCES users (id),
        start_lat       double precision NOT NULL
            CONSTRAINT rides_start_lat_check CHECK (start_lat BETWEEN -90 AND 90),
        start_lng       double precision NOT NULL
            CONSTRAINT rides_start_lng_check CHECK (start_lng BETWEEN -180 AND 180),
        start_address   varchar(255)  NOT NULL,
        end_lat         double precision NOT NULL
            CONSTRAINT rides_end_lat_check CHECK (end_lat BETWEEN -90 AND 90),
        end_lng         double precision NOT NULL
            CONSTRAINT rides_end_lng_check CHECK (end_lng BETWEEN -180 AND 180),
        end_address     varchar(255)  NOT NULL,
        departure_time  timestamptz   NOT NULL,
        capacity        integer       NOT NULL
            CONSTRAINT rides_capacity_check CHECK (capacity BETWEEN 1 AND 8),
        available_seats integer       NOT NULL,
        price_per_seat  numeric(10,2) NOT NULL
            CONSTRAINT rides_price_per_seat_check CHECK (price_per_seat >= 0),
        status          varchar(20)   NOT NULL DEFAULT 'upcoming'
            CONSTRAINT rides_status_check
            CHECK (status IN ('upcoming', 'full', 'in_progress', 'completed', 'cancelled')),
        preferences     jsonb,
        notes           text,
        created_at      timestamptz   NOT NULL DEFAULT now(),
        updated_at      timestamptz   NOT NULL DEFAULT now(),
        CONSTRAINT rides_seats_range CHECK (available_seats BETWEEN 0 AND capacity)
    )
    """,
    "CREATE INDEX rides_driver_idx ON rides (driver_id, departure_time)",
    "CREATE INDEX rides_start_idx ON rides (start_lat, start_lng)",
    "CREATE INDEX rides_end_idx ON rides (end_lat, end_lng)",
    "CREATE INDEX rides_departure_idx ON rides (departure_time)",
    "CREATE INDEX rides_status_dep_idx ON rides (status, departure_time)",
    """
    CREATE TRIGGER rides_set_updated_at BEFORE UPDATE ON rides
        FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """,
    # ── ride_requests ──
    """
    CREATE TABLE ride_requests (
        id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ride_id         integer     NOT NULL REFERENCES rides (id),
        passenger_id    integer     NOT NULL REFERENCES users (id),
        seats_requested integer     NOT NULL DEFAULT 1
            CONSTRAINT ride_requests_seats_requested_check
            CHECK (seats_requested BETWEEN 1 AND 8),
        status          varchar(20) NOT NULL DEFAULT 'pending'
            CONSTRAINT ride_requests_status_check
            CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
        requested_at    timestamptz NOT NULL DEFAULT now(),
        responded_at    timestamptz
    )
    """,
    # One non-cancelled request per passenger per ride (CONTRACT.md §8, D2).
    """
    CREATE UNIQUE INDEX ride_requests_active_uq
        ON ride_requests (ride_id, passenger_id)
        WHERE status IN ('pending', 'approved', 'rejected')
    """,
    "CREATE INDEX ride_requests_ride_idx ON ride_requests (ride_id, status)",
    "CREATE INDEX ride_requests_passenger_idx ON ride_requests (passenger_id, status)",
    # ── ratings ──
    """
    CREATE TABLE ratings (
        id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ride_id      integer     NOT NULL REFERENCES rides (id),
        from_user_id integer     NOT NULL REFERENCES users (id),
        to_user_id   integer     NOT NULL REFERENCES users (id),
        role_rated   varchar(20) NOT NULL
            CONSTRAINT ratings_role_rated_check CHECK (role_rated IN ('driver', 'passenger')),
        score        integer     NOT NULL
            CONSTRAINT ratings_score_check CHECK (score BETWEEN 1 AND 5),
        comment      text,
        tags         jsonb       NOT NULL DEFAULT '[]'::jsonb,
        created_at   timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ratings_one_per_direction UNIQUE (ride_id, from_user_id, to_user_id),
        CONSTRAINT ratings_not_self CHECK (from_user_id <> to_user_id)
    )
    """,
    "CREATE INDEX ratings_to_user_idx ON ratings (to_user_id, role_rated, created_at DESC)",
    # ── notifications ──
    """
    CREATE TABLE notifications (
        id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id             integer      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        type                varchar(50)  NOT NULL,
        title               varchar(200) NOT NULL,
        message             text         NOT NULL,
        related_entity_type varchar(20)
            CONSTRAINT notifications_related_entity_type_check
            CHECK (related_entity_type IN ('ride', 'ride_request')),
        related_entity_id   integer,
        is_read             boolean      NOT NULL DEFAULT false,
        created_at          timestamptz  NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX notifications_feed_idx ON notifications (user_id, is_read, created_at DESC)",
)

DOWNGRADE_STATEMENTS = (
    "DROP TABLE IF EXISTS notifications",
    "DROP TABLE IF EXISTS ratings",
    "DROP TABLE IF EXISTS ride_requests",
    "DROP TABLE IF EXISTS rides",
    "DROP TABLE IF EXISTS clerk_webhook_events",
    "DROP TABLE IF EXISTS users",
    "DROP FUNCTION IF EXISTS set_updated_at()",
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
